<?php
/**
 * @file
 * A description of what your module does.
 */
//  drupal_add_js(libraries_get_path('node_modules') . '/@angular/forms/bundles/forms.umd.js');
  drupal_add_css('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css');
function angular_init() {


}

function angular_menu() {
  $items = [];
  $items['angular2'] = [
    'access callback' => TRUE,
    'page callback' => 'angular_callback',
  ];
  $items['angular2/delete/%'] = array(
    'page callback' => 'angular_delete_user_ajax_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['angular2/rename/%/%'] = array(
    'page callback' => 'angular_rename_user_ajax_callback',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function angular_rename_user_ajax_callback($userId, $newName) {

  if ($userId != 1) {


    $user = user_load($userId);
    $user->name = $newName;
    $user = user_save($user);
    return '1';
  }

}

function angular_delete_user_ajax_callback($userId) {
  if ($userId != 1) {
    $user = user_load($userId);
    $user->name = 'User-' . $userId;
    $user = user_save($user);
    return '1';
  }


}

function angular_callback() {
  $build = [];
//  global $user;
//  $users = entity_load('user');
//  dpm($users);
//  drupal_add_js(array('angular' => $user), 'setting');
//  drupal_add_js(array('users' => $users), 'setting');


  $build['content'] = [
    '#theme' => [
      'angular_component',
    ],
    '#attached' => [
      'js' => [
        libraries_get_path('node_modules') . '/core-js/client/shim.min.js',
        libraries_get_path('node_modules') . '/zone.js/dist/zone.js',
        libraries_get_path('node_modules') . '/reflect-metadata/Reflect.js',
        libraries_get_path('node_modules') . '/rxjs/bundles/Rx.js',
        libraries_get_path('node_modules') . '/@angular/core/bundles/core.umd.js',
        libraries_get_path('node_modules') . '/@angular/forms/bundles/forms.umd.js',
        libraries_get_path('node_modules') . '/@angular/common/bundles/common.umd.js',
        libraries_get_path('node_modules') . '/@angular/compiler/bundles/compiler.umd.js',
        libraries_get_path('node_modules') . '/@angular/platform-browser/bundles/platform-browser.umd.js',
        libraries_get_path('node_modules') . '/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
        drupal_get_path('module', 'angular') . '/angular.component.js',
        drupal_get_path('module', 'angular') . '/angular.module.js',
        drupal_get_path('module', 'angular') . '/angular.main.js',
      ],
    ],
  ];
  return $build;
}

function angular_theme($existing, $type, $theme, $path) {
  return [
    'angular_component' => [
      'template' => 'angular-component',
      'variables' => array(),
      'path' => drupal_get_path('module', 'angular') . '/theme',
    ],
  ];
}